### ISSUE TITLE
Cant use keyboard shortcuts to switch pane

### ISSUE THREAD

**Issue by QuentinDela** [domagojk/serverless-console#1]
Hello, 

Thanks for this extension, it's pretty cool. 
Sometimes the switch panes shortcut won't work : Shift + Command + }

**Comment by domagojk** [comment]
hey @QuentinDela 
I think I have different key bindings. So just to be sure, are you referring to
"workbench.action.switchWindow" command (as defined in "Keyboard Shortcut Preferences")?

**Comment by domagojk** [comment]
I'm closing this since I wasn't able to reproduce it.
For anyone experiencing this, feel free to reopen the issue.
