### ISSUE TITLE
FeatureRequest: Option AWS profile over the stage

### ISSUE THREAD

**Issue by GMGOD** [domagojk/serverless-console#13]
On our company we use two set of accounts, one for QA and another for PROD, in that case we use different set of key's for QA and PROD. From that i will love to select the AWS profile as an option over the stage so we can change profile independing of the service.

**Comment by domagojk** [comment]
Thanks for the review :) 
Sure, I can add that 👍

**Comment by domagojk** [comment]
Added in version 0.6.2

However, UI when adding service is still the same. So for now, if you want to enable this you need to edit your `settings.json` file in vscode.

for example if the source is `serverlessFramework`, instead of
```json
"stages": [
   "test",
   "dev",
   "prod"
 ]
```

you can define:
```json
"stages": [
  {
    "stage": "test",
    "awsProfile": "default"
  },
  {
    "stage": "dev",
    "awsProfile": "different-profile"
  },
  {
    "stage": "prod",
    "awsProfile": "different-profile"
  }
]
```
