### ISSUE TITLE
FeatureRequest: AWS Logs group dropdown limited to 50

### ISSUE THREAD

**Issue by QuentinDela** [domagojk/serverless-console#15]
Hello, 

It looks like the drop down for AWS Logs group is limited to 50.
I wish to at least be able to copy paste my log group path in the UI.

The actual workaround is to come back the serverlessConsole settings JSON.

Thanks

**Comment by domagojk** [comment]
Autocomplete component in the UI is from https://ant.design/ and it is not a small change to allow text + dropdown with autocomplete, so I have increased a log list limit to 500.
Hope that is sufficient
