### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by lHumanizado** [domagojk/serverless-console#17]
When i associate a new dynamodb table when i open an item and close the table the association stops working and shows this error:

![image](https://user-images.githubusercontent.com/22862693/82392694-86360f00-9a12-11ea-8358-c84861086873.png)

I tried deleting the association and creating it again but the error shows immediately, this occurs whit any table, only when i open an item, tried reinstalling the plugin but didn't work either, im not able to use those tables again

**Comment by domagojk** [comment]
@lHumanizado thanks for reporting this!
The issue should be fixed in version 0.6.18
