### ISSUE TITLE
function name = undefined-stage-name when service name is undefined

### ISSUE THREAD

**Issue by reidkersey** [domagojk/serverless-console#2]
If a serverless.yaml file is written like `service: myServiceName` instead of the standard 
```
service:
  name: myServiceName
```
then when you go to add a project with Serverless Console, the title of the functions that it tires to pull will be `undefined-stage-functionName` instead of `myServiceName-stage-functionName`

This is true whether or not Title is set as `Use config service name` or if something custom is inserted.

**Comment by domagojk** [comment]
@reidkersey Thank you for the detailed bug report!
It should be fixed in ver 0.4.9
