### ISSUE TITLE
Allow free text search for service resources

### ISSUE THREAD

**Issue by rafaelrodrigues3092** [domagojk/serverless-console#27]
While trying to look for cloudformation deployments and/or cloudwatch log groups almost every time I cannot find my resources (accounts are flooded with thousands and thousands of resources)
I have seen an identical issue opened in the past for log groups, however, rather than always choosing from the list, would it be possible to allow free text in case the resource is not found?

**Comment by domagojk** [comment]
Dropdowns used for log groups or clodformation have the ability to search:
<img width="534" alt="Screenshot 2020-06-24 at 10 14 33" src="https://user-images.githubusercontent.com/1868852/85520755-9f2e7300-b603-11ea-8ca6-b8ae14c418ad.png">

Isn't that what you are asking for?

**Comment by rafaelrodrigues3092** [comment]
Not exactly. The AWS accounts i work with have a ton of cloudformation deloyments. when i type the name of my cloudformation, i usually don't find it. I assume it's because there's a limit on the number of entries in the list.
What i was thinking is that if the list doesn't have the cloudformation of interest, we can free text it and still add the service.

my workaround at the moment is adding the cloudformation entries directly on the settings file, and that does the trick

**Comment by domagojk** [comment]
I have added an option to switch between dropdown and normal input (version 0.6.25):
<img width="442" alt="Screenshot 2020-06-29 at 13 12 18" src="https://user-images.githubusercontent.com/1868852/85998455-249e9280-ba0b-11ea-8a38-db3888d5cac7.png">
