### ISSUE TITLE
sls ENOENT with VS Code Remote

### ISSUE THREAD

**Issue by sav-valerio** [domagojk/serverless-console#3]
Hello,
I'm trying to use the extension with VS Code Remote (I'm using an Ubuntu 19.04 box via SSH) but I'm getting the following error:

```
spawn sls ENOENT

ENOENT error sometimes occur when command is not found.
Make sure "sls" can be executed in "/home/user/git/projects/test"
```

The extension has been installed in the remote box and Serverless Framework can be launched in the mentioned folder.

Any clues?
Thanks

**Comment by domagojk** [comment]
@sav-valerio this sounds like an error not related to the extension itself (since it only executes the command and prints the output).

Can you maybe try replacing `sls print` command with `./node_modules/serverless/bin/serverless print` and see if it's the same?

**Comment by sav-valerio** [comment]
I'm using the standalone version of the Serverless Framework which is installed in the `/home/user/.serverless/bin/serverless` folder.

I changed the print command to that path and the command works now, but now I'm having some workspace related problems.
I'll create new issues.

**Comment by domagojk** [comment]
@sav-valerio ok, and thanks for your bug reports!
