### ISSUE TITLE
FeatureRequest: Support DynamoDB running locally

### ISSUE THREAD

**Issue by jasonkochel** [domagojk/serverless-console#30]
DynamoDB can be run in "local" mode (via Docker container) and accessed at localhost:8000.  It would be great for this tool to offer that as a "region" to connect to (as the AWS Explorer for VS 2019 does).

Thanks for an awesome extension.  The DynamoDB experience is better than the official AWS SDK!

**Comment by domagojk** [comment]
@jasonkochel Thanks for the suggestion. Local DynamoDb support is added in version 0.7.0!

**Comment by joaspacce** [comment]
Hi. Im using DynamoDB via Docker container and I can't see the tables in the serverless-console, but I can see it from the aws cli. The extension is great! How can I debug the issue and find why can't see the tables?

**Comment by domagojk** [comment]
Hey @joaspacce, I'm glad you like it.
You can try this to debug the issue:

```
git clone https://github.com/domagojk/serverless-console sls-console
cd sls-console
git checkout debug
npm i
```

now open `src/dynamoDb/webviewCommands/listDynamoDbTables.ts` and set a breakpoint (for example on line 30)
go to "Run" and choose "run extension".

When new window opens up, try to reproduce the error and see if you see any errors in a "debug console"

**Comment by joaspacce** [comment]
Hi @domagojk. I found the issue, is `Cannot do operations on a non-existent table`. 

You need to create the docker image passing these flags `-jar DynamoDBLocal.jar -sharedDb`.

If someone has the same problem, this is what I'm using:
```
docker run --name dynamo-container -p 8042:8000 -d amazon/dynamodb-local -jar DynamoDBLocal.jar -sharedDb
```

Thanks again for the extension!

**Comment by domagojk** [comment]
@jasonkochel thanks for the report 👍 I will add some kind of error output when adding DynamDb so there is no need for debugging the extension.
