### ISSUE TITLE
Error: "The specified log group does not exist"

### ISSUE THREAD

**Issue by icaptnbob** [domagojk/serverless-console#32]
This extension is failing to find prod Cloud logs but works for dev stage. It was working at the end of August. Nothing has changed in the serverless.yml file since then. 
I keep getting this message when I go to the prod stage of any lambda function: "The specified log group does not exist."
The dev stage shows the current logs.

The prod stage logs are visible in AWS Cloudwatch for all of these.

This seems to coincide with the extension change 0.7.2. Is there anything I can do to debug?

_Originally posted by @icaptnbob in https://github.com/domagojk/serverless-console/issues/31#issuecomment-693172892_

**Comment by icaptnbob** [comment]
I have confirmed this is caused by 0.7.2 by installing previous versions.
0.7.2 - only dev stage finds shows Lambda Cloudwatch log files for the APIs. prod gives the error "The specified log group does not exist."
0.7.1 - both dev and prod stage fail with this: "The specified log group does not exist."
0.7.0 - works correctly for both prod and dev stages.

**Comment by domagojk** [comment]
Thank you for reporting this. I have published version 0.7.3 which is actually the same as 0.7.0.
I'm closing this issue and reopening #31
