### ISSUE TITLE
Any plans on upgrading?

### ISSUE THREAD

**Issue by paulbijancoch** [domagojk/serverless-console#37]
Hey @domagojk 
this tool looks really promising, and and I would love to integrate it into my development setup.

When installing I get:

`Unable to install 'devadvice.serverlessconsole' extension because it is not compatible with the current version of VS Code (version 1.35.0).`

Are there any plans to upgrade it?

Unfortunately I do not have any experience in working with vs.code extensions, so I have no clue on what needed to be done, to make it work again.

Sincerely ✌️

**Comment by domagojk** [comment]
I can't reproduce the issue. But it seems that your VS Code needs upgrading. At the moment, latest vs code version is 1.53, version 1.35.0 is from May 2019 :)

**Comment by paulbijancoch** [comment]
😄😄 makes totally sense.
Thanks for your help ✌🏼
