### ISSUE TITLE
Invalid path on Windows

### ISSUE THREAD

**Issue by reidkersey** [domagojk/serverless-console#4]
When run in VS Code on windows, the relative path starts with a `\` and therefore can not execute the serverless command.

Example: Relative directory = `\backend`
Output =
```
 spawn serverless ENOENT


ENOENT error sometimes occur when command is not found.
            Make sure "serverless" can be executed in "\C:\Users\reidk\Documents\Git\projectR\backend"`
```
Serverless is able to be executed in `C:\Users\reidk\Documents\Git\projectR\backend`

It appears that the extra \ before C: is coming from the command `vscode.workspace.workspaceFolders[0].uri.path` 

My VSCode version is 1.41.1

Also, I should let you know that I absolutely love this extension. Thanks for all of your hard work!

----EDIT----
Also appears to have the same problem with VSCode version 1.39.2

----EDIT 2----
I cloned the code and tried removing the `\` myself, and it did not seem to have any effect. Starting to think there may be a different problem here.

----EDIT 3----
I am all out of ideas on what the problem is. For some reason, it is not executing the `serverless print` command in windows, but that command is able to be executed via the terminal in the same directory. I had originally thought that it was related to the path beginning in a '\' but when I edit `settings.ts` to return `path.join(workspaceDir, conf.cwd).substring(1)` it does not seem to have any effect. Maybe there is some other place path is used that I am not aware of? Or maybe something else is going wrong, or maybe I'm just a crazy person who is having problems that are specific to my environment only...

----Edit 4----
~~Last edit for the night...~~ I tried the extension on another windows computer, with the same result of getting the ENOENT error

----EDIT 5----
Tried the suggestion in another issue of running the command from where it is installed (in my case  `C:\Users\reidk\AppData\Roaming\npm`) with no positive results, just got back the same ENOENT error the print command was `C:\Users\reidk\AppData\Roaming\npm\serverless print`

**Comment by domagojk** [comment]
I see, thanks for reporting it. I will fix this next week

pet, 24. sij 2020. 23:29 reidkersey <notifications@github.com> je napisao:

**Comment by domagojk** [comment]
@reidkersey thank you for your help! You were correct about the path returned from settings, but there was an additional issue with node spawn on windows, which is addressed in [cross-spawn](https://www.npmjs.com/package/cross-spawn).

So please check if ver 0.5.4 has fixed the issue for you
