### ISSUE TITLE
Where and how too setup aws credentials ? I use variable environement for my code it work, but for serverless idk.

### ISSUE THREAD

**Issue by PrincesseLulu** [domagojk/serverless-console#42]

**Comment by domagojk** [comment]
You need to have AWS credentials file, which is usually set up with [aws cli](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)

If you prefer UI solution, you can do it with [AWS toolkit extension for vs code](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) and then when you try to connect to AWS you should get this kind of promt:

<img width="466" alt="Screen Shot 2021-05-17 at 10 42 28" src="https://user-images.githubusercontent.com/1868852/118460541-175ec500-b6fd-11eb-9990-e4bed5ac115a.png">

After setting up your profile you can use it in serverless console extension
