### ISSUE TITLE
Not working - Cannot add any service

### ISSUE THREAD

**Issue by sweepy84** [domagojk/serverless-console#53]
Whenever I try to add any service (SLS Framework, Cloudformation, DynamoDB) it runs and says "Service successfully added" but I don't see anything in the side view...just says "Click to add a service..."

Tried reloading window and restarting.

**Comment by sweepy84** [comment]
Has something to do with Workspaces or Monorepos... or both - because I ran it in a fresh folder and it worked.

Please help.

**Comment by domagojk** [comment]
It is hard to say what is the issue without reproducing it. If you have some repository where I can test it out I can check it out.

My frist guess is that something is messed up in `.vscode/settings.json` under `serverlessConsole.services`. You can maybe check that file in both working and non-working instances and see if you can spot anything wrong. You can even try to copy/paste a working settings and see if it works in your monorepo

**Comment by sweepy84** [comment]
Ok did a bunch of trial an error until I found the problem settings. It breaks and doesn't add the service to config is you have this setting in your existing config:
`		"files.exclude": {
			"**/dist/**"
		}`

**Comment by sweepy84** [comment]
oh boy - that's my bad, there was an error in my config, the dist exclusion above should end with a : true.
So weird all my other extensions have been working.... but when I fix this it works.
Sorry!!

**Comment by domagojk** [comment]
Np, I'm glad you solved it! 🙂
