### ISSUE TITLE
[vscode] command 'serverlessConsole.addService' not found

### ISSUE THREAD

**Issue by eloyola** [domagojk/serverless-console#58]
Hi @all,
I added the extension to vscode and serverless console panel shows a "You have not yet openend a folder" when I tried to Add service I'm having the following error: 
command 'serverlessConsole.addService' not found

Windows 11: Build 22000.1098 | VsCode 1.73.1
#aws --version
aws-cli/2.8.9 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

Same error on macOS Ventura 13.0.1

**Comment by domagojk** [comment]
"You have not yet openend a folder" error means you need to first open a working directory in vscode (file->open folder). Have you done that?

**Comment by eloyola** [comment]
yes, main issue is "command 'serverlessConsole.addService' not found"

**Comment by eloyola** [comment]
fixed on mac, just reinstalled the vscode and its extension
