### ISSUE TITLE
Problems with variables

### ISSUE THREAD

**Issue by marceloabk** [domagojk/serverless-console#6]
I have a project where I use variables from env and opt like:

`${opt:stage}`
`${env:SOME_ENV}`

currently there are no way to set these var, are there?

**Comment by domagojk** [comment]
@marceloabk you can set the opt variables by specifing it in the command
<img width="818" alt="Screenshot 2020-02-12 at 20 02 55" src="https://user-images.githubusercontent.com/1868852/74367784-bc8c3e80-4dd2-11ea-9953-d61cb30e76fb.png">

but for environment variables, it seems that `export VAR=x && sls print` is not working, so I will add an additional field for that in the next version. Thanks for the heads up

**Comment by domagojk** [comment]
@marceloabk support for environment variables is added in version 0.5.6.
If there is any issue with it, feel free to reopen the issue.
