### ISSUE TITLE
Feature Requests: Allow using AWS Identity Center credentials

### ISSUE THREAD

**Issue by jacintoArias** [domagojk/serverless-console#64]
There is a new recommended way to work with AWS credentials in dev machines using AWS Identity credentials and AWS CLI v2.

Now when authenticating using `aws sso` you can retrieve temporal credentials using secure browser sign on. The new profiles are stored in the aws `config` file and have a different syntax than previously key or role based credentials.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

It should be nice to include them as valid credentials for the extension.

**Comment by domagojk** [comment]
Well I guess it is never too late? 🥲 
This was added in version 0.8.0
