### ISSUE TITLE
"Serverless Information" log sections are detected as errors

### ISSUE THREAD

**Issue by sav-valerio** [domagojk/serverless-console#7]
I'm trying to add some of my services to the extension.

I usually get the "Serverless Information" messages related to SSM but they're not critical, the services work just fine.

Still, when I try to click on '**Add service**' it just stays there.
I'm getting the output from `serverless print` with the "_Informations_" section, and below that I'm seeing the the service info as it should be.

I also tried to add another service (that does not use SSM so I won't any "Information" messages), and it works perfectly.

Any clues?
Thanks!

![image](https://user-images.githubusercontent.com/14777542/74960119-08129e00-540c-11ea-9f4d-4b24da9f089d.png)

**Comment by domagojk** [comment]
Yes, it is because yaml parser has troubles parsing that output. I will try to reproduce this and see what I can do. In the meantime, have you maybe tried using "Cloudformation" as a source rather than serverless framework?

**Comment by domagojk** [comment]
@sav-valerio I've tried using "serverless-dotenv" plugin and managed to reproduce the issue. Can you please check if version 0.5.7 works for you too?

**Comment by sav-valerio** [comment]
Works perfectly.
Thanks you so much!
