### ISSUE TITLE
Region selector for the Serverless Framework source

### ISSUE THREAD

**Issue by sav-valerio** [domagojk/serverless-console#8]
I have few deployments of the same Lambda functions on multiple regions.
With the [Serverless Framework CLI](https://serverless.com/framework/docs/providers/aws/cli-reference/deploy/) I can specify the region like this:
```zsh
sls deploy --region us-east-1
or
sls logs helloFunction --region eu-west-1
```

I'm not able to to the same thing within the extension (when using Serverless Framework as the source).

I tried to work around this by setting the `AWS_REGION` env variable and setting the `region` parameter in the _Serverless Print_ command, but the displayed logs are still retrieved from `us-east-1`.

[Checking out the code](https://github.com/domagojk/serverless-console/blob/f9b31343ee374de16e7d124e2ee4c16c14e614c2/src/serviceGenerators/serverlessFrameworkService.ts) I found out that the region value is retrieved from the `provider` section available in the config .yml file, but I don't have that parameter because I'm setting the regions using the CLI option.

Any chance for adding some kind of selector, like the one present in the Cloudformation source?
Thanks!

**Comment by domagojk** [comment]
I'm a bit hesitant to make a UI for it since this seems like an edge case, but I've just published a version 0.5.8 where `region` parameter is not ignored, you will just have to define it in your `.vscode/settings.json`.

```json
{
  "serverlessConsole.services": [
    {
      "type": "serverlessFramework",
      "awsProfile": "default",
      "region": "eu-west-1",
      "cwd": "./",
      "command": "serverless print",
      "timeOffsetInMs": 0,
      "stages": [
        "dev",
        "prod"
      ]
    }
]
```
